# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0006_auto_20161212_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='\n        Language choices and translations will be displayed in this\n        order\n        ', unique=True),
        ),
    ]

